apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: demo
spec:
  containers:
    - name: linux
      image: alpine:latest
      command: ["sleep", "infinity"]
      env:
       - name: USER 
         valueFrom:
            configMapKeyRef:
               name: config-1
               key: name
      envFrom:
        - configMapRef:
            name: config-1
      volumeMounts:
         - name: config
           mountPath: "/opt"
           readOnly: true

         - name: config-2
           mountPath: "/opt/nginx"
           readOnly: true

  volumes:
  - name: config
    configMap:
      name: config-1
      items:
      - key: "config.txt"
        path: "env.txt"
      - key: "config-1.txt"
        path: "env-1.txt"

  - name: config-2
    configMap:
      name: config-2
      items:
      - key: "nginx.conf"
        path: "nginx.conf"


