apiVersion: v1
kind: ConfigMap
metadata:
  name: config-1
  namespace: demo
data:
  nginx.json: hello i ma json
  nginx1.json: hello i ma json 2

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: demo
spec:
  containers:
    - name: linux
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
         - name: config
           mountPath: "/opt"
           readOnly: true

  volumes:
  - name: config
    configMap:
      name: config-1
      items:
      - key: "nginx1.json"
        path: "key1.json"







