- name: Update the system
  apt:
    update_cache: yes 

- name: Upgrade the system
  apt:
    upgrade: dist
    autoremove: yes

- name: Install necessary softwares
  apt:
    name:
      - nginx
      - wget
      - curl
      - net-tools
      - ca-certificates
    state: present

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and install Docker GPG key
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker repository to Apt sources
  ansible.builtin.shell: |
        echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update Apt cache
  apt:
    update_cache: yes

- name: Install docker and compose 
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin 
      - gnupg
    state: present

- name: starting and enabling docker and nginx services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - nginx
    - docker




