apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-east-2

nodeGroups:
  - name: new-subnet-nodegroup
    instanceType: t2.medium
    desiredCapacity: 1

    



    


